version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  build:
    commands:
      - echo Packaging Lambda function
      - zip lambdazip lambda.py
artifacts:
  files:
    - lambda.zip
