version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - cd lambda-test
      - zip -r ../lambda-deployment-package.zip .

      
  post_build:
    commands:
      - echo Build completed on `date`
      - cd lambda-test

artifacts:
  files:
    - lambda-deployment-package.zip
