version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      # No zip command here, just keep the files as is
      - ls -l  # Optional: list files to verify

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - lambda.py
    - buildspec.yml
