version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r ../lambda-deployment-package.zip .
      - unzip -l ../lambda-deployment-package.zip   # <-- Add this here to list ZIP content
      
  post_build:
    commands:
      - echo Build completed on `date`
      - cd lambda-test

artifacts:
  files:
    - lambda-deployment-package.zip
