version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip -r lambda-deployment-package.zip lambda.py buildspec.yml
      - unzip -l lambda-deployment-package.zip

  post_build:
    commands:
      - echo Build completed on `date`
      

artifacts:
  files:
    - lambda-deployment-package.zip
