version: 0.2

phases:
  build:
    commands:
      - zip -r function.zip .
  post_build:
    commands:
      - aws lambda update-function-code --function-name lambda-test-func --zip-file fileb://function.zip
artifacts:
  files:
    - function.zip
