version: 0.2

phases:
 build:
    commands:
      - echo Build started on `date`
      - echo Packaging Lambda function...
      # Zip the lambda.py file (and any dependencies if applicable)
      - zip lambda.zip lambda.py
 post_build:
    commands:
      - echo Build completed on `date`
      - ls -l  # List files to verify lambda.zip exists

artifacts:
  files:
    - lambda.zip