version: 0.2

phases:
  build:
    commands:
      - echo "Zipping lambda.py from parent directory with no folder structure"
      - zip -j function.zip ../../lambda.py
  post_build:
    commands:
      - echo "Updating Lambda function code"
      - aws lambda update-function-code --function-name lambda-test-func --zip-file fileb://function.zip --region us-east-1

artifacts:
  files:
    - function.zip
