version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - zip lambda-deployment-package.zip lambda.py
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - lambda-deployment-package.zip
